apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guacamole
  annotations:
    kubernetes.io/ingress.class: nginx  
    cert-manager.io/issuer: letsencrypt-prod
    cert-manager.io/issuer-kind: ClusterIssuer
  namespace: guacamole
spec:  
  tls:
    - hosts:
        - guacamole.127.0.0.1.nip.io
      secretName: tls-guacamole-ingress
