apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- ingress.yml
patches:
- path: ingress-patch.yml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: guacamole
    namespace: guacamole
    version: v1
images:
- name: maxwaldorf/guacamole
  newName: maxwaldorf/guacamole
  newTag: 1.4.2
