kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: guacamole-pvc
  namespace: uptime-kuma
  labels:
    app: guacamole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
